import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          id="mobile nav"
          className="flex z-10 sm:invisible items-center justify-between font-mono text-sm fixed top-5 left-[50%] translate-x-[-50%] w-[80%] gap-5 backdrop-blur-md bg-black text-white rounded-full py-3 px-4"
        >
          <div id="links" className="flex gap-5 pl-4">
            <Link href={""}>Home</Link>
            <Link href={""}>Contact</Link>
          </div>
          <Link
            className="bg-white text-black px-3 py-1.5 rounded-2xl"
            href={""}
          >
            Sign Up
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
